package com.academy.auth.constant;

public enum EventType {
    EMAIL_VERIFICATION,
    EMAIL_VERIFICATION_SUCCESS,
    EMAIL_VERIFICATION_FAILURE,
    PASSWORD_RESET,
    REFRESH_TOKEN_UPDATE,
    ACCESS_TOKEN_UPDATE,
    TOKEN_REMOVE

}
